# fly.toml app configuration file generated for f3s on 2024-09-14T13:54:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'f3s'
primary_region = 'nrt'

[build]
  [build.args]
    GO_VERSION = '1.23'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
