# fly.toml app configuration file generated for f3s-api on 2024-09-20T16:34:56+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'f3s-api'
primary_region = 'nrt'

[env]
  PORT = '8081'

[http_service]
  internal_port = 0
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
