# fly.toml app configuration file generated for f3s-api on 2024-09-20T16:34:56+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'f3s-api'
primary_region = 'nrt'

[env]
  PORT = '8080'

[[vm]]
  size = 'shared-cpu-2x'
