// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Battery struct {
	ID              int64
	NodeID          sql.NullInt64
	Level           sql.NullInt64
	ChargingTime    sql.NullInt64
	DischargingTime sql.NullInt64
	Charging        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type EntryLog struct {
	ID        int64
	NodeID    sql.NullInt64
	VisitorID sql.NullInt64
	Type      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ExhibitionLog struct {
	ID        int64
	NodeID    sql.NullInt64
	VisitorID sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Food struct {
	ID        int64
	NodeID    sql.NullInt64
	Name      string
	Price     int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type FoodStallLog struct {
	ID        int64
	NodeID    sql.NullInt64
	VisitorID sql.NullInt64
	FoodID    sql.NullInt64
	Quantity  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Node struct {
	ID        int64
	Key       sql.NullString
	Name      string
	Ip        sql.NullString
	Type      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Student struct {
	ID        int64
	VisitorID sql.NullInt64
	Grade     int64
	Class     int64
	StudentID int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Visitor struct {
	ID        int64
	Random    int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Ip        string
}
